# Generated by Django 5.1.4 on 2024-12-06 19:15

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("network", "0002_contact_product_remove_networknode_city_and_more"),
    ]

    operations = [
        migrations.AlterField(
            model_name="networknode",
            name="products",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.CASCADE, to="network.product"
            ),
        ),
    ]
