# Generated by Django 5.1.4 on 2024-12-06 19:36

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("network", "0003_alter_networknode_products"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="networknode",
            name="products",
        ),
        migrations.AddField(
            model_name="networknode",
            name="products",
            field=models.ManyToManyField(blank=True, to="network.product"),
        ),
    ]
