# Generated by Django 5.1.4 on 2024-12-06 19:56

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("network", "0004_remove_networknode_products_networknode_products"),
    ]

    operations = [
        migrations.AlterField(
            model_name="networknode",
            name="name",
            field=models.CharField(max_length=100, unique=True),
        ),
    ]
